services:
  app:
    image: node:lts-bookworm
    working_dir: /app
    container_name: fsd_app
    user: root
    volumes:
      - .:/app
      - ./docker/entrypoint.sh:/entrypoint.sh
    deploy:
      resources:
        limits:
          memory: 1G
    env_file:
      - .env
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

  link:
    image: oven/bun:latest
    working_dir: /fantastic_link
    container_name: fsd_link
    user: root
    volumes:
      - ./fantastic-link:/fantastic_link
      - ./fantastic-link/docker/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    ports:
      - "51642:51642"

  browser:
    image: jacoblincool/playwright:firefox-server-1.53.1
    container_name: fsd_browser
    ports:
      - "53333:53333"
    shm_size: 3gb

  api:
    image: node:lts-bookworm
    working_dir: /app
    container_name: fsd_api
    user: root
    volumes:
      - ./api:/app
      - ./api/docker/entrypoint.sh:/entrypoint.sh
    env_file:
      - ./api/.env
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    ports:
      - 8055:8055
    dns:
      - 8.8.8.8
      - 9.9.9.9
